version: '3.1'

services:  
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8086:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
