export const GET_PRODUCTS_RESUME = 'GET_PRODUCTS_RESUME'
export const SAVE_PRODUCT = 'SAVE_PRODUCT'
export const GET_PRODUCTS_RESUME_SUCCESS = 'GET_PRODUCTS_RESUME_SUCCESS'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'